export const REQUEST_BOARDS = "REQUEST_BOARDS";
export const RECEIVE_BOARDS = "RECEIVE_BOARDS";

export const CHANGE_CURR_BOARD = "CHANGE_CURR_BOARD";

export const REQUEST_POSTS = "REQUEST_POSTS";
export const RECEIVE_POSTS = "RECEIVE_POSTS";