export const REQUEST_BOARDS = "REQUEST_BOARDS";
export const RECEIVE_BOARDS = "RECEIVE_BOARDS";

export const CHANGE_CURR_BOARD = "CHANGE_CURR_BOARD";

export const REQUEST_POSTS = "REQUEST_POSTS";
export const RECEIVE_POSTS = "RECEIVE_POSTS";

export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const REQUEST_ADD_COMMENT = "REQUEST_ADD_COMMENTS";
export const ADDED_COMMENT = "ADDED_COMMENT";